### ISSUE TITLE
CodingHistory assemblage in Airtable does not descriminate between Asset Action Log types

### ISSUE THREAD

**Issue by hocksteindw** [brnco/avmpi_scripts#7]
SIA000592_A0006DM_01.wav is a good example.

Physical assets can have multiple associated Asset Actions.  Sometimes (e.g. cleaning, etc), equipment is added to these types of asset actions to log the machine used. This makes its way into the CodingHistory field since the AirTable concatenation used does not discriminate between the "A-D Transfer" action and other types of Asset Actions. When there is no equipment associated with the non-transfer record, this adds an extra space.

The CodingHistory information drawn from the Asset Action Log fields needs an "if" statement that will draw only from either "A-D Transfer" or "Digital Transfer" types of Asset Actions.

**Comment by brnco** [comment]
Give this a look when you can. There were actually two issues here, where the Airtable formula wasn't ignoring non-transfer actions and, separately, (and I'm including this info for my notes) a whitespace character was getting inserted into a lookup field downstream from that, in Physical Assets -> BWF TextFS - Analogue. Solved that whitespace issue with TRIM({field} & "") because TRIM() doesn't work on raw lookup fields, you have to add a (blank) string
